import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./(components)/header/Navigation";
import SocietyMark from "./(components)/footer/SocietyMark";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${inter.variable} font-inter antialiased`}
      >
       <Navigation />
       <main>
         {children}
       </main>
       
      </body>
   <footer className="bg-[#f8fafc] text-center text-gray-700 text-sm py-6 mt-8 border-t border-gray-200">
        <div className="flex flex-col items-center gap-2">
          <SocietyMark />
          <div className="mt-2">
            <span className="block font-semibold">N° de SIRET 832 217 657 000 17</span>
            <span className="block mt-1">En aucun cas la sophrologie ne remplace un traitement ou un avis médical</span>
            <span className="block mt-1">© 2023. FABRICI CATHERINE. All Rights Reserved.</span>
          </div>
        </div>
      </footer>
    </html>
  );
}
